enum Status : uint8 {
    Ok,
    TooLong,
    InvalidRequest,
    SessionAlreadyExist,
    //...
}

table Version {
    major: uint16;
    minor: uint16;
    patch: uint16;
    build: string;
}

table PlatformInfo {
    cpu_arch: string;
    platform: string;
    version: string;
}

enum AuthType : ubyte (bit_flags) {
    NoAuth,
    Password,
    Login,
    Token
}

struct Common {
    api_version: uint8 = 0;
}

table RequestBase {
    common: Common (required);
}

table ResponseBase {
    common: Common (required);
    status: Status = Ok;
}