include "../common.fbs";

namespace v1;

union Request {
    AuthRequest,
    FetchRequest,
    FetchAllRequest,
    NeedAuthRequest,
    PullRequest,
    StatusRequest,
    VersionRequest
}

table AuthRequest {
    type: AuthType;
    payload: [byte];
    login: string;
}

table FetchRequest {
    token: [byte];
    depth: uint32 = 1;
    platform_info: PlatformInfo;
    package_name: string;
}

table FetchAllRequest {
    token: [byte];
    depth: uint32 = 1;
}

table NeedAuthRequest {}

table PullRequest {
    token: [byte];
    package_uid: uint64;
}

table StatusRequest {}
table VersionRequest {}

table RootRequest {
    base: RequestBase;
    request: Request;
}

root_type RootRequest;